steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    git submodule update --init --recursive
    nvm install 8.9.1
    nvm use 8.9.1
    npm i -g yarn
  displayName: 'preinstall'

- script: |
    export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0
    sh -e /etc/init.d/xvfb start
    sleep 3
  displayName: 'Linux preinstall'
  condition: eq(variables['Agent.OS'], 'Linux')

- script: |
    yarn
  displayName:  'Install'

- script: |
    node_modules/.bin/gulp electron
    node_modules/.bin/gulp compile --max_old_space_size=4096
    node_modules/.bin/gulp optimize-vscode --max_old_space_size=4096
  displayName: 'Scripts'

- script: |
    ./scripts/test.sh --reporter mocha-junit-reporter
  displayName: 'Tests'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/test-results.xml'
  condition: succeededOrFailed()

- script: |
    yarn run tslint
  displayName: 'Run TSLint'