name: On Label
on:
  issues:
    types: [labeled]

jobs:
  processLabelAction:
    permissions:
      issues: write
    name: Process Label Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Process Label Action
        uses: hramos/label-actions@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
